# Generated by Django 5.0.4 on 2024-05-20 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_job_profile_delete_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='first_name',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_name',
        ),
    ]
